import { LaptopSession, phoneConnectionCard, bindPairing, renderPhoneConnection, savedLaptopSession } from "./phone-connection";
import { soundFrameSchema, type SoundFrame } from "../sound/contracts";
import { BottleToneDetector, calculateAirVolume, analyzeBottleRelationship, type BottlePoint } from "../bottle-analysis";
import type { State } from "../contracts";
import "./bottle.css";

type Trial = BottlePoint & { waterVolumeMl:number; savedAt:string };
export function bottle(root:HTMLElement) {
  root.innerHTML=`<div class="site-shell bottle-lab"><header class="topbar"><a class="brand" href="/" aria-label="PocketLab STEM"><img class="brand-mark" src="/pocketlab-logo.png" alt=""><strong>PocketLab</strong><span>STEM</span></a><nav class="main-navigation" aria-label="Главная навигация"><a href="/pendulum">Маятник</a><a href="/sound">Увидь свой голос</a><a class="active" aria-current="page" href="/bottle">Собери музыкальный инструмент</a></nav></header>
  <main id="top"><div class="hero"><div class="hero-icon" aria-hidden="true"><img src="/bottle-logo.png" alt=""></div><div class="hero-title"><h1>Собери музыкальный инструмент</h1><p>Меняй количество воды в бутылке и узнай, как меняется её звук.</p></div></div>
  <div class="experiment-layout"><aside class="sidebar">${phoneConnectionCard}<section class="card bottle-tips"><h2>Подготовь бутылку</h2><ul><li>Используй одну бутылку во всей серии.</li><li>Дуй поперёк горлышка, не внутрь.</li><li>Старайся держать ровный тон.</li><li>Избегай громкого фонового шума.</li></ul></section>
  <details class="card reference-card bottle-reference"><summary><strong>Справочник</strong><span class="reference-chevron">▾</span></summary><div class="reference-content"><div class="reference-item"><h3>Что происходит в бутылке</h3><p>Воздух внутри бутылки колеблется, когда ты дуешь поперёк горлышка. Бутылка усиливает звук около своей резонансной частоты.</p></div><div class="reference-item"><h3>Что такое резонанс</h3><p>Резонанс — усиление колебаний на частоте, к которой система особенно чувствительна.</p></div><div class="reference-item"><h3>Почему вода меняет звук</h3><p>Вода вытесняет воздух. В этой бутылке геометрия остаётся той же, а объём воздуха меняется. Измерения могут показать, как частота связана с этим объёмом.</p></div><div class="reference-item"><h3>Что такое частота</h3><p>Частота — число колебаний за секунду, измеряется в герцах (Гц). Частота выше — звук выше.</p></div><div class="reference-item"><h3>Почему нужен устойчивый тон</h3><p>Вдох, шум и короткий звук не дают надёжного результата. PocketLab сохраняет частоту только после непрерывного устойчивого тона.</p></div><div class="reference-item"><h3>Как правильно дуть</h3><p>Дуй поперёк края горлышка, создай ровный поток и постарайся удержать звучание. Держи телефон рядом, но не закрывай его микрофон.</p></div><div class="reference-item"><h3>Почему измерения могут отличаться</h3><p>Влияют уровень воды, форма горлышка, направление и сила потока, расстояние до телефона и фоновый шум. Используй ту же бутылку и отмеряй воду аккуратно.</p></div></div></details>
  </aside>
  <div class="main-workspace is-locked" id="bottle-workspace" aria-disabled="true"><section id="bottle-lock" class="card bottle-lock"><span class="wizard-kicker">ШАГ 1 · ПОДКЛЮЧЕНИЕ</span><h2>Подключите телефон, чтобы начать</h2><p>Создайте сессию в карточке слева. После подключения можно будет задать условие и измерить звук.</p></section>
  <section class="card stage-card bottle-stage-card" aria-label="Этапы эксперимента"><button class="stage is-active" data-bottle-step="setup"><span class="stage-icon">1</span><span><strong>Условие</strong><small>Бутылка и вода</small></span></button><span class="stage-arrow">›</span><button class="stage is-locked" data-bottle-step="series" disabled><span class="stage-icon">2</span><span><strong>Измерения</strong><small>Серия и связь</small></span></button><span class="stage-arrow">›</span><button class="stage is-locked" data-bottle-step="prediction" disabled><span class="stage-icon">3</span><span><strong>Предсказание</strong><small>Проверка модели</small></span></button></section>
  <section class="card bottle-condition" data-bottle-panel="setup"><div class="condition-heading"><div><span class="wizard-kicker">ШАГ 1 · УСЛОВИЕ ОПЫТА</span><h2>Бутылка и количество воды</h2></div></div>
    <div class="bottle-setup"><label>Объём бутылки<div class="bottle-input"><input id="capacity" type="number" min="1" value="500" aria-label="Объём бутылки в миллилитрах"><span>мл</span></div></label></div>
    <div class="bottle-stage"><div class="bottle-illustration" aria-label="Уровень воды в бутылке"><div class="bottle-neck"></div><div class="bottle-body"><div id="water-fill" class="water-fill"></div><span class="air-label">ВОЗДУХ</span><span class="water-label">ВОДА</span></div></div>
      <div class="condition-values"><label>Количество воды<div class="bottle-input water-input"><input id="water" type="number" min="0" value="100" aria-label="Количество воды в миллилитрах"><span>мл</span></div></label><p id="volume-error" class="field-error" role="alert"></p><div class="volume-readouts"><div><span>Вода</span><strong id="water-readout">100 мл</strong></div><div><span>Воздух</span><strong id="air-readout">400 мл</strong></div></div></div></div>
    <div class="measure-row"><div><span class="wizard-kicker">ИЗМЕРЕНИЕ</span><p id="measure-status" role="status">Подключи телефон и разреши микрофон.</p></div><strong id="frequency-result" class="frequency-result">— <small>Гц</small></strong></div>
    <div class="wizard-actions"><button id="measure-start" class="button-primary">Начать измерение</button><button id="measure-stop" class="button-secondary" hidden>Остановить</button><button id="measure-save" class="button-primary" hidden>Сохранить измерение</button><button id="measure-repeat" class="button-secondary" hidden>Повторить</button></div>
  </section>
  <section class="card bottle-series" data-bottle-panel="series" hidden><div class="section-heading"><div><span class="wizard-kicker">ШАГ 2 · ТВОИ НАБЛЮДЕНИЯ</span><h2>Серия измерений</h2><p id="series-count">Пока нет сохранённых измерений.</p></div></div><div class="table-scroll"><table><thead><tr><th>Вода, мл</th><th>Воздух, мл</th><th>Частота, Гц</th></tr></thead><tbody id="trial-rows"></tbody></table></div><div class="bottle-graph-wrap"><div class="graph-heading"><h3>Частота от объёма воздуха</h3><span><i class="measured-dot"></i> Измерения <i class="model-line"></i> Модель</span></div><canvas id="bottle-graph" aria-label="График измеренной частоты в зависимости от объёма воздуха"></canvas></div>
    <div id="discovery" class="discovery" aria-live="polite"><span class="wizard-kicker">ПОИСК СВЯЗИ</span><h3 id="discovery-title">Сохрани измерения при четырёх разных уровнях воды.</h3><p id="discovery-copy">Тогда PocketLab проверит, какую зависимость поддерживают именно твои данные.</p></div>
    <div class="wizard-actions"><button id="next-measurement" class="button-primary">Следующее измерение</button><button id="open-prediction" class="button-secondary" hidden>Предсказать звук</button></div>
  </section>
  <section id="prediction" class="card prediction-card" data-bottle-panel="prediction" hidden><span class="wizard-kicker">ШАГ 3 · ПРОВЕРЬ СВОЮ МОДЕЛЬ</span><h2>Предскажи звук</h2><p>Выбери частоту — оценим объём воздуха по измерениям твоей бутылки.</p><div class="prediction-data"><strong id="prediction-data-title">Измерения твоей серии</strong><div id="prediction-points" class="prediction-points"></div><p id="prediction-model" class="muted"></p></div><label>Желаемая частота<div class="bottle-input"><input id="target-frequency" type="number" min="1" value="440" aria-label="Желаемая частота"><span>Гц</span></div></label><p id="prediction-result" class="prediction-result">—</p><button id="check-prediction" class="button-primary">Проверить предсказание</button><div id="prediction-check" class="prediction-check" hidden></div></section>
  </div></div></main></div>`;
  const el=(id:string)=>root.querySelector<HTMLElement>(`#${id}`)!, btn=(id:string)=>el(id) as HTMLButtonElement;
  let socket:LaptopSession|undefined, session="", connected=false, ready=false, state:State="DISCONNECTED", activeStep="setup", capacity=0, bottleLocked=false, trialWater=100, detector=new BottleToneDetector(), detected:number|null=null, saved:Trial[]=[], target:number|null=null, noiseSum=0,noiseCount=0,noise=-60,calibrationStart=0;
  const pair=bindPairing(root,()=>session);
  const setState=(next:State,message:string)=>{state=next;el("measure-status").textContent=message;socket?.send({type:"state",state,message});render();};
  function render(){renderPhoneConnection(root,connected,!!socket?.connected,session);const measuring=state==="CALIBRATING"||state==="MEASURING";(el("capacity") as HTMLInputElement).disabled=bottleLocked;(el("water") as HTMLInputElement).disabled=measuring;btn("measure-start").textContent=saved.length?"Следующее измерение":"Начать измерение";btn("measure-start").disabled=!connected||!ready||measuring||!!detected;btn("measure-start").hidden=measuring||!!detected;btn("measure-stop").hidden=!measuring;btn("measure-save").hidden=detected===null;btn("measure-repeat").hidden=detected===null;renderStep();}
  function renderStep(){const relationship=analyzeBottleRelationship(saved),canSeries=connected&&saved.length>0,canPredict=connected&&relationship.supported;el("bottle-workspace").classList.toggle("is-locked",!connected);el("bottle-workspace").setAttribute("aria-disabled",String(!connected));el("bottle-lock").hidden=connected;root.querySelector<HTMLElement>(".bottle-stage-card")!.hidden=!connected;root.querySelectorAll<HTMLElement>("[data-bottle-panel]").forEach(panel=>{const step=panel.dataset.bottlePanel!,available=step==="setup"?connected:step==="series"?canSeries:canPredict;panel.hidden=!available||activeStep!==step;});root.querySelectorAll<HTMLButtonElement>("[data-bottle-step]").forEach(button=>{const step=button.dataset.bottleStep!,available=step==="setup"?connected:step==="series"?canSeries:canPredict;button.disabled=!available;button.classList.toggle("is-locked",!available);button.classList.toggle("is-active",activeStep===step&&available);button.classList.toggle("is-complete",available&&activeStep!==step);});btn("open-prediction").hidden=!canPredict;el("prediction-data-title").textContent=`Измерения твоей серии · ${relationship.distinctConditions} условий`;el("prediction-points").innerHTML=relationship.points.map(point=>`<span><i></i>${point.airVolumeMl} мл → ${point.frequencyHz.toFixed(0)} Гц</span>`).join("");el("prediction-model").textContent=relationship.fit?`Модель: f ∝ V${relationship.fit.exponent<0?`⁽${relationship.fit.exponent.toFixed(2)}⁾`:``} · R² ${relationship.fit.rSquared?.toFixed(2)??"—"}`:"";}
  function showStep(step:string){activeStep=step;renderStep();}
  root.querySelectorAll<HTMLButtonElement>("[data-bottle-step]").forEach(button=>button.addEventListener("click",()=>{if(!button.disabled)showStep(button.dataset.bottleStep!);}));
  btn("next-measurement").onclick=()=>showStep("setup");
  btn("open-prediction").onclick=()=>showStep("prediction");
  function volumes(){const waterInput=el("water") as HTMLInputElement, capInput=el("capacity") as HTMLInputElement;try{const effectiveCapacity=bottleLocked?capacity:Number(capInput.value),water=Number(waterInput.value),air=calculateAirVolume(effectiveCapacity,water);trialWater=water;el("volume-error").textContent="";el("water-readout").textContent=`${water} мл`;el("air-readout").textContent=`${air} мл`;el("water-fill").setAttribute("style",`height:${Math.max(0,Math.min(100,water/effectiveCapacity*100))}%`);return air;}catch(error){el("volume-error").textContent=(error as Error).message;return null;}}
  (el("water") as HTMLInputElement).addEventListener("input",()=>{volumes();detected=null;el("frequency-result").innerHTML="— <small>Гц</small>";render();});
  (el("capacity") as HTMLInputElement).addEventListener("input",()=>{if(!bottleLocked)volumes();});
  btn("create").onclick=()=>{socket?.close();session="";connected=ready=false;socket=new LaptopSession("bottle",m=>{if(m.type==="session"){session=m.code;connected=m.phoneConnected;ready=!!m.capabilities?.microphone;el("session").textContent=session;el("pair").hidden=false;pair();setState(connected?"CONNECTED":"DISCONNECTED",connected?"Телефон подключён. Проверь готовность микрофона.":"Подключите телефон через QR-код.");}if(m.type==="peer"){connected=m.connected;if(!connected){ready=false;if(state==="MEASURING"||state==="CALIBRATING")setState("DISCONNECTED","Телефон отключён. Измерение прервано.");}render();}if(m.type==="capabilities")ready=m.microphone;if(m.type==="sound-ready"){ready=m.ready;render();}if(m.type==="status")el("phone-status").textContent=m.message;if(m.type==="interruption"||m.type==="stop"){detector.reset();detected=null;setState("STOPPED",m.reason||"Измерение прервано.");}if(m.type==="error")el("error").textContent=m.message;if(m.type==="sound-frame"&&(state==="CALIBRATING"||state==="MEASURING")){const parsed=soundFrameSchema.safeParse(m.frame);if(!parsed.success)return;const f=parsed.data;if(state==="CALIBRATING"){if(!noiseCount)calibrationStart=f.timestamp;noiseSum+=10**(f.level/10);noiseCount++;if(f.timestamp-calibrationStart>=1200){noise=10*Math.log10(noiseSum/noiseCount);detector=new BottleToneDetector(noise);setState("MEASURING","Слушаю… подуй поперёк горлышка бутылки.");}return;}const tone=detector.add(f);el("measure-status").textContent=f.level<Math.max(-55,noise+7)?"Слишком тихо. Поднеси телефон ближе.":f.pitch?"Слушаю… ищу устойчивый тон.":"Тон не найден. Попробуй ровно подуть над горлышком.";if(tone){detected=tone.frequencyHz;el("frequency-result").innerHTML=`${detected.toFixed(0)} <small>Гц</small>`;setState("STOPPED","Стабильный сигнал. Частота измерена автоматически.");if(target!==null){const delta=Math.abs(detected-target);const check=el("prediction-check");check.hidden=false;check.innerHTML=`<strong>Цель ${target.toFixed(0)} Гц · Измерено ${detected.toFixed(0)} Гц · Разница ${delta.toFixed(0)} Гц</strong>`;target=null;}}}render();},online=>{if(!online){connected=ready=false;render();}});render();};
  btn("measure-start").onclick=()=>{if(volumes()===null||!connected||!ready)return;if(!bottleLocked){capacity=Number((el("capacity") as HTMLInputElement).value);bottleLocked=true;render();}detected=null;noiseSum=noiseCount=0;noise=-60;detector.reset();el("frequency-result").innerHTML="— <small>Гц</small>";setState("CALIBRATING","Подготовка микрофона… сохрани тишину.");};
  btn("measure-stop").onclick=()=>{detector.reset();detected=null;setState("STOPPED","Измерение остановлено.");};
  btn("measure-repeat").onclick=()=>{detected=null;el("frequency-result").innerHTML="— <small>Гц</small>";setState("CONNECTED","Готово к повторному измерению.");render();};
  btn("measure-save").onclick=()=>{if(detected===null)return;const water=Number((el("water") as HTMLInputElement).value),air=calculateAirVolume(capacity,water);saved.push({waterVolumeMl:water,airVolumeMl:air,frequencyHz:detected,savedAt:new Date().toISOString()});detected=null;activeStep="series";el("frequency-result").innerHTML="— <small>Гц</small>";renderSeries();setState("CONNECTED","Измерение сохранено. Измени количество воды для следующей точки.");render();};
  function renderSeries(){const rows=el("trial-rows");rows.innerHTML=saved.map(t=>`<tr><td>${t.waterVolumeMl}</td><td>${t.airVolumeMl}</td><td>${t.frequencyHz.toFixed(0)}</td></tr>`).join("");const analysis=analyzeBottleRelationship(saved);el("series-count").textContent=`Сохранено измерений: ${saved.length} · разных условий: ${analysis.distinctConditions}`;el("discovery-title").textContent=analysis.fit?(analysis.supported?`Твои данные согласуются со степенной зависимостью f ∝ V${analysis.fit.exponent<0?`⁽${analysis.fit.exponent.toFixed(2)}⁾`:``}.`:`Пока не удалось надёжно подтвердить ожидаемую зависимость.`):`Сохрани измерения при ${Math.max(0,4-analysis.distinctConditions)} разных уровнях воды.`;el("discovery-copy").textContent=analysis.fit?`Модель рассчитана по медианам твоих измерений (R² ${analysis.fit.rSquared?.toFixed(2)??"—"}). Точки на графике — измерения, линия — модель.`:"Повторные измерения при одном уровне помогают увидеть разброс, для анализа нужны разные объёмы воздуха.";draw();renderStep();}
  (el("target-frequency") as HTMLInputElement).addEventListener("input",()=>{const a=analyzeBottleRelationship(saved);const targetHz=Number((el("target-frequency") as HTMLInputElement).value),air=a.prediction(targetHz);if(air===null||air>=capacity){target=null;el("prediction-result").textContent="Эта частота находится слишком далеко от измеренного диапазона для этой бутылки.";return;}target=targetHz;const water=capacity-air;el("prediction-result").textContent=`Попробуй оставить около ${Math.round(air)} мл воздуха и налить примерно ${Math.round(water)} мл воды.`;(el("water") as HTMLInputElement).value=String(Math.round(water));volumes();});
  btn("check-prediction").onclick=()=>{if(target===null){el("prediction-result").textContent="Введи частоту в допустимом диапазоне.";return;}const check=el("prediction-check");check.hidden=false;check.innerHTML=`<strong>Измени воду до ${Math.round(Number((el("water") as HTMLInputElement).value))} мл и измерь реальный звук.</strong><button id="run-prediction" class="button-primary">Начать проверку</button>`;check.querySelector("button")!.onclick=()=>{showStep("setup");btn("measure-start").click();};};
  function draw(){const canvas=el("bottle-graph") as HTMLCanvasElement,w=canvas.clientWidth||650,h=290,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext("2d")!;c.scale(dpr,dpr);c.clearRect(0,0,w,h);const points=analyzeBottleRelationship(saved).points,pad={l:56,r:18,t:24,b:42};c.font="12px system-ui";c.fillStyle="#69758a";c.fillText("Частота, Гц",5,15);c.fillText("Объём воздуха, мл",w/2-45,h-5);for(let i=0;i<=4;i++){const y=pad.t+i*(h-pad.t-pad.b)/4;c.strokeStyle="#e8e6e2";c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();}if(!points.length){c.fillText("Сохрани первое измерение — оно появится здесь",pad.l+8,h/2);return;}const xmin=Math.min(...points.map(p=>p.airVolumeMl)),xmax=Math.max(...points.map(p=>p.airVolumeMl)),ymin=Math.min(...points.map(p=>p.frequencyHz),0),ymax=Math.max(...points.map(p=>p.frequencyHz))*1.1,px=(x:number)=>pad.l+(x-xmin)/Math.max(1,xmax-xmin)*(w-pad.l-pad.r),py=(y:number)=>h-pad.b-(y-ymin)/Math.max(1,ymax-ymin)*(h-pad.t-pad.b);const fit=analyzeBottleRelationship(saved).fit;if(fit){c.strokeStyle="#e87925";c.setLineDash([6,5]);c.lineWidth=2;c.beginPath();for(let i=0;i<=50;i++){const x=xmin+(xmax-xmin)*i/50,y=fit.amplitude*x**fit.exponent;i?c.lineTo(px(x),py(y)):c.moveTo(px(x),py(y));}c.stroke();c.setLineDash([]);}for(const p of saved){c.fillStyle="#315da8";c.beginPath();c.arc(px(p.airVolumeMl),py(p.frequencyHz),5,0,Math.PI*2);c.fill();}}
  new ResizeObserver(draw).observe(el("bottle-graph"));window.addEventListener("resize",draw);window.addEventListener("pagehide",()=>socket?.close());
  el("availability").textContent="Микрофон ожидает подключения";el("rate").hidden=true;volumes();renderSeries();render();if(savedLaptopSession())btn("create").click();
}
