import "./landing.css";
import { mountLandingVisual } from "./landing-visual";

const pendulum = `<svg viewBox="0 0 230 116" role="img" aria-label="Маятник и график колебаний"><path d="M24 22h178M104 22l-38 58m38-58 45 58" fill="none" stroke="#c9c5bc" stroke-width="2"/><circle cx="104" cy="22" r="6" fill="#a96b45"/><circle cx="66" cy="80" r="10" fill="#f2692e"/><circle cx="149" cy="80" r="10" fill="#e4e0da"/><path d="M26 100h176M34 100c13 0 13-50 26-50s13 50 26 50 13-50 26-50 13 50 26 50 13-50 26-50 13 50 26 50" fill="none" stroke="#f2692e" stroke-width="2.6" stroke-linecap="round"/></svg>`;
const voice = `<svg viewBox="0 0 240 116" role="img" aria-label="Звуковая волна"><path d="M8 56h14l9-9 7 20 9-49 10 82 10-74 9 57 9-41 9 22 8-14 9 5 8-10 9 18 9-31 9 45 8-33 9 15 9-10h24" fill="none" stroke="#f2692e" stroke-width="3" stroke-linejoin="round" stroke-linecap="round"/><path d="M8 98h220" stroke="#dedbd4" stroke-width="1"/></svg>`;
const bottles = `<svg viewBox="0 0 248 116" role="img" aria-label="Бутылки с разным уровнем воды"><g fill="none" stroke="#526786" stroke-width="2"><path d="M27 22h10v17l12 13v44H15V52l12-13zM82 16h10v23l12 13v44H70V52l12-13zM137 24h10v15l12 13v44h-34V52l12-13zM192 9h10v30l12 13v43h-34V52l12-13z"/></g><path d="M17 72h30v22H17zm55-7h30v29H72zm55-17h30v46h-30zm55 1h30v45h-30z" fill="#82a9dd"/><path d="M17 72h30v22H17z" fill="#f2692e"/><path d="M7 108h223" stroke="#dedbd4"/></svg>`;
const instrument = `<svg viewBox="0 0 248 116" role="img" aria-label="Самодельный ксилофон"><g transform="rotate(7 111 58)"><path d="M37 31v54M64 25v60M91 20v65M118 25v60M145 31v54M172 37v48" stroke="#b77a56" stroke-width="18" stroke-linecap="round"/><path d="M37 31v54M64 25v60M91 20v65M118 25v60M145 31v54M172 37v48" stroke="#eebc8d" stroke-width="13" stroke-linecap="round"/></g><path d="m178 18 42 60" stroke="#172c4d" stroke-width="5" stroke-linecap="round"/><circle cx="173" cy="14" r="8" fill="#bd805c"/><path d="M206 98c10-2 10-26 20-26s10 30 20 30" fill="none" stroke="#889bb5" stroke-width="2"/></svg>`;

export function landing(root: HTMLElement) {
  root.innerHTML = `<div class="landing" id="top">
    <header class="landing-nav"><a class="landing-brand" href="/" aria-label="PocketLab STEM — главная"><img src="/pocketlab-logo.png" alt=""><span>PocketLab</span><i>STEM</i></a><nav aria-label="Основная навигация"><a href="#experiments">Эксперименты</a><a href="#how">Как это работает</a><a href="#phone">Возможности телефона</a></nav><a class="nav-cta" href="/pendulum">Открыть лабораторию <span>↗</span></a></header>
    <main>
      <section class="landing-hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow"><span></span> ЛАБОРАТОРИЯ В ТВОЁМ КАРМАНЕ</p><h1 id="hero-title">А что, если<br>измерить это?</h1><p class="hero-lede">Маятник качается. Бутылка звучит. Телефон превращает любопытство в настоящие данные.</p><div class="hero-actions"><a class="action-primary" href="/pendulum">Запустить эксперимент <span>↗</span></a><a class="action-text" href="#experiments">Выбрать лабораторию <span>↓</span></a></div><div class="hero-note"><span class="note-mark">✳</span><span>Три лаборатории уже открыты<br><b>Никакого специального оборудования</b></span></div></div><div class="hero-art hero-art--alive"><canvas class="landing-visual" aria-label="Анимированный маятник, звуковая волна и телефон в лаборатории"></canvas><div class="visual-label visual-label--top"><i></i> MOTION / LIVE CAPTURE</div><div class="visual-label visual-label--bottom"><b>01</b><span>КОЛЕБАНИЕ</span><small>0.84 s</small></div><div class="visual-orbital orbital-one"></div><div class="visual-orbital orbital-two"></div></div></section>
      <section class="how-section" id="how"><div class="section-heading"><div><p class="eyebrow">ТВОЯ ЛАБОРАТОРИЯ</p><h2>От наблюдения к открытию</h2></div><p class="heading-aside">Каждый опыт начинается с простого вопроса.<br>Дальше — твои данные и твои выводы.</p></div><div class="steps"><article class="step"><span class="step-no">01</span><span class="step-icon icon-phone">▯</span><div><h3>Подключи телефон</h3><p>Открой ссылку на смартфоне — он передаст данные датчиков прямо в лабораторию.</p></div></article><span class="step-arrow">↗</span><article class="step"><span class="step-no">02</span><span class="step-icon icon-grid">⊞</span><div><h3>Выбери эксперимент</h3><p>Маятник, голос или собственный инструмент. Для каждого опыта есть подсказки.</p></div></article><span class="step-arrow">↗</span><article class="step"><span class="step-no">03</span><span class="step-icon icon-chart">▥</span><div><h3>Найди закономерность</h3><p>Собирай измерения, смотри на графики и объясняй, что произошло.</p></div></article></div></section>
      <section class="experiments-section" id="experiments"><div class="section-heading experiment-heading"><div><p class="eyebrow">ВЫБЕРИ, ЧТО ИССЛЕДОВАТЬ</p><h2>Эксперименты</h2></div><span class="availability"><i></i> 3 лаборатории открыты</span></div><div class="experiment-grid"><a class="experiment-card card-pendulum" href="/pendulum"><div class="card-art">${pendulum}</div><div class="card-meta"><span>01</span><span>МЕХАНИКА</span></div><h3>Маятник</h3><p>Измерь период колебаний и проверь, как на него влияет длина нити.</p><span class="card-link">Начать опыт <b>↗</b></span></a><a class="experiment-card card-voice" href="/sound"><div class="card-art">${voice}</div><div class="card-meta"><span>02</span><span>АКУСТИКА</span></div><h3>Увидь свой голос</h3><p>Запиши звук и рассмотри частоты, из которых складывается голос.</p><span class="card-link">Начать опыт <b>↗</b></span></a><a class="experiment-card card-instrument" href="/bottle"><div class="card-art">${instrument}</div><div class="card-meta"><span>03</span><span>РЕЗОНАНС</span></div><h3>Собери инструмент</h3><p>Настрой бутылки водой, создай мелодию и исследуй высоту звука.</p><span class="card-link">Начать опыт <b>↗</b></span></a></div><div class="coming-row"><span class="coming-symbol">＋</span><p><b>Лаборатория продолжает расти.</b> Новые опыты скоро появятся здесь.</p><span class="coming-label">СКОРО</span></div></section>
      <section class="phone-section" id="phone"><div class="phone-copy"><p class="eyebrow">ИНСТРУМЕНТЫ УЖЕ С ТОБОЙ</p><h2>Смартфон —<br>маленькая лаборатория</h2><p>Акселерометр улавливает движение. Микрофон слышит колебания. Камера помогает наблюдать. PocketLab собирает их вместе — чтобы физику можно было не только читать, но и проверять.</p><a href="/pendulum" class="action-text">Попробовать сейчас <span>→</span></a></div><div class="sensor-map"><div class="sensor-phone"><div class="sensor-screen"><img src="/pocketlab-logo.png" alt=""><span>PocketLab</span><small>ДАТЧИКИ ТЕЛЕФОНА</small><div class="mini-chart"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></div></div><div class="sensor-label sensor-motion"><b>↝</b><span><strong>Движение</strong><small>Акселерометр и гироскоп</small></span></div><div class="sensor-label sensor-sound"><b>∿</b><span><strong>Звук</strong><small>Микрофон телефона</small></span></div><div class="sensor-label sensor-camera"><b>◎</b><span><strong>Изображение</strong><small>Камера для наблюдений</small></span></div><div class="sensor-label sensor-graph"><b>▥</b><span><strong>Графики</strong><small>Данные в реальном времени</small></span></div><svg viewBox="0 0 630 340" aria-hidden="true"><path d="M165 98h85q20 0 32 18l17 29M165 239h85q20 0 32-16l17-27m90-99h62q23 0 32-16m-94 174h63q24 0 33 17"/></svg></div></section>
    </main><footer class="landing-footer"><a class="landing-brand" href="#top"><img src="/pocketlab-logo.png" alt=""><span>PocketLab</span><i>STEM</i></a><span>Физика начинается с вопроса.</span><div><a href="#how">Как это работает</a><a href="#experiments">Эксперименты</a><a href="/pendulum">Открыть лабораторию</a></div><small>© PocketLab STEM</small></footer></div>`;
  const visual = root.querySelector<HTMLCanvasElement>(".landing-visual");
  if (visual) mountLandingVisual(visual);
}
